apiVersion: v1
kind: Service
metadata: 
  name: frontend
  namespace: frontend
spec:
  ports:
  - port: 80
    targetPort: 5000   
    protocol: TCP
  type: LoadBalancer
  selector:
    role: frontend
